# Dezelfde basis als het buggy-project van de les Desktop Environment:
# Ubuntu 24.04 met gcc, clang, cmake, gdb en valgrind voorgeïnstalleerd.
FROM mcr.microsoft.com/devcontainers/cpp:1-ubuntu-24.04
