# Source: https://github.com/tcort/github-action-markdown-link-check
# Actions documentation: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: Check Markdown links

on:
  push: # Check modified files on push
    paths-ignore:
      - './_slidev/**'
  schedule: # Check all files monthly (temporarily set for testing)
    - cron: '0 0 1 * *' # At 00:00 on day-of-month 1 (monthly)

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        # Fetch full history for proper diff comparison
        fetch-depth: 0
        
    - name: Run markdown link check on individual files
      run: |
        # Set quiet mode based on event type
        if [ "${{ github.event_name }}" == "push" ]; then
          QUIET_FLAG="--quiet"
        else
          QUIET_FLAG=""
        fi
        
        HAS_ERRORS=false
        
        # Find all markdown files excluding _slidev folder
        find . -name "*.md" -not -path "./_slidev/*" -print0 | while IFS= read -r -d '' file; do
          echo "Checking: $file"
          if npx markdown-link-check "$file" --config .markdown-link-check.json $QUIET_FLAG; then
            echo "✅ $file passed"
          else
            echo "❌ Error in file: $file"
            HAS_ERRORS=true
          fi
        done
        
        if [ "$HAS_ERRORS" = true ]; then
          echo "❌ Some files had link errors"
          exit 1
        else
          echo "✅ All files passed"
        fi
      shell: bash
